### ISSUE TITLE
Core dump thrown when certain systems are specified

### ISSUE THREAD

**Issue by m-squared96** [m-squared96/PyPLANE#37]
Certain systems cause the app to crash, citing `Aborted (core dumped)`, when the "Plot" button is clicked.

I have seen several systems cause this bug, but I can only quote one currently: with the default system specified, change the value of the "a" parameter from 2 to 0.5 and click "Plot". On my machine, the app crashes as specified above. 

What exactly causes this to happen is unclear, but it appears to be a NumPy error of some form.

**Comment by m-squared96** [comment]
Output from above scenario:

```
Traceback (most recent call last):
  File "source/ui_main_window.py", line 244, in plot_button_clicked
    self.update_psp(phase_coords, passed_params)
  File "source/ui_main_window.py", line 267, in update_psp
    system_of_eqns, axes_limits=((x_min, x_max), (y_min, y_max))
  File "/home/mikie/Programming/Python/pyplanedev/branches/feature_iss27_defaults/PyPLANE/source/trajectory.py", line 94, in update_system
    self.generate_meshes()
  File "/home/mikie/Programming/Python/pyplanedev/branches/feature_iss27_defaults/PyPLANE/source/trajectory.py", line 221, in generate_meshes
    Rprime = self.system.phasespace_eval(t=None, r=R)
  File "/home/mikie/Programming/Python/pyplanedev/branches/feature_iss27_defaults/PyPLANE/source/equations.py", line 131, in phasespace_eval
    return tuple(eqn.eval_rhs(t=t, r=r) for eqn in self.equations)
  File "/home/mikie/Programming/Python/pyplanedev/branches/feature_iss27_defaults/PyPLANE/source/equations.py", line 131, in <genexpr>
    return tuple(eqn.eval_rhs(t=t, r=r) for eqn in self.equations)
  File "/home/mikie/Programming/Python/pyplanedev/branches/feature_iss27_defaults/PyPLANE/source/equations.py", line 74, in eval_rhs
    return self.func(t, r, **self.param_values)
  File "<lambdifygenerated-5>", line 3, in _lambdifygenerated
numpy.core._exceptions.UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
Aborted (core dumped)
```

**Comment by m-squared96** [comment]
Expanding on this, it appears that the `core dumped` error arises when any user-specified system including parameters is passed.
Emphasis is placed on the "user-defined"; bizarrely, the default system works fine until the user clicks "Plot" to, say, refresh the plot or change a parameter.

**Comment by mjancen** [comment]
Was this issue present before PR #36 ?

**Comment by m-squared96** [comment]
No, you're right I've established the cause of the error and resolved it. The regression arose from that PR as I was sending the parameter values to SOE as strings...embarrassing. 
Anyway as far as I can see that's solved the issue, will test more thoroughly and update.

**Comment by m-squared96** [comment]
Seems good, closing
