### ISSUE TITLE
isfinite error on certain functions

### ISSUE THREAD

**Issue by jcosmos0** [m-squared96/PyPLANE#66]
PyPLANE crashes when you set y' and x' to a constant (perhaps an error message will work instead to say it is non-computable).

**Comment by jcosmos0** [comment]
Here's the traceback:

Traceback (most recent call last):
  File "/Users/USER/PyPLANE/PyPLANE/ui_main_window.py", line 456, in plot_button_clicked
    self.update_psp(phase_coords, passed_params)
  File "/Users/USER/PyPLANE/PyPLANE/ui_main_window.py", line 491, in update_psp
    self.phase_plot.init_space(
  File "/Users/USER/PyPLANE/PyPLANE/trajectory.py", line 526, in init_space
    self.draw_quiver()
  File "/Users/USER/PyPLANE/PyPLANE/trajectory.py", line 558, in draw_quiver
    self.quiver = self.ax.quiver(
  File "/Users/USER/usr/local/bin/homebrew/lib/python3.9/site-packages/matplotlib/__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/USER/usr/local/bin/homebrew/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5021, in quiver
    q = mquiver.Quiver(self, *args, **kw)
  File "/Users/moses.joshua/usr/local/bin/homebrew/lib/python3.9/site-packages/matplotlib/quiver.py", line 503, in __init__
    self.set_UVC(U, V, C)
  File "/Users/USER/usr/local/bin/homebrew/lib/python3.9/site-packages/matplotlib/quiver.py", line 570, in set_UVC
    U = ma.masked_invalid(U, copy=True).ravel()
  File "/Users/USER/usr/local/bin/homebrew/lib/python3.9/site-packages/numpy/ma/core.py", line 2371, in masked_invalid
    condition = ~(np.isfinite(a))
